repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=50000"] # 50 MB

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      # Lint first; allow quick autofix on staged files only.
      - id: ruff-check
        args: ["--fix"]
        types_or: [python, pyi, jupyter]
      # Then format (idempotent; fast).
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  # Run tests on pre-push instead of pre-commit to keep commit latency low.
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: python3 -m pytest -q -m "not integration_test"
        pass_filenames: false
        stages: [pre-push]
        always_run: true
