[project]
name = "ai-tinkerers-hackathon"
version = "0.1.0"
description = "AI Tinkerers x Google Cloud Hackathon Project"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pytest>=8.4.2",
]
